-- 43. 查询下周过生日的学生
SELECT * from student
WHERE WEEKOFYEAR(Sage) = WEEKOFYEAR(ADDDATE(CURDATE(),INTERVAL 1 WEEK))

-- 支持跨年处理
SELECT * from student
WHERE WEEKOFYEAR('2025-01-01') = WEEKOFYEAR(ADDDATE('2024-12-27',INTERVAL 1 WEEK))
